"""create_profiles

Revision ID: 95cfd386e7f4
Revises: a4cc42930aff
Create Date: 2026-06-26 23:15:56.590526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '95cfd386e7f4'
down_revision: Union[str, Sequence[str], None] = 'a4cc42930aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('resume', 'manual', 'linkedin_import', name='profilesource'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
