"""create_job_preferences

Revision ID: cd472e359c35
Revises: 95cfd386e7f4
Create Date: 2026-06-26 23:21:49.829599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd472e359c35'
down_revision: Union[str, Sequence[str], None] = '95cfd386e7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_roles', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('experience_level', sa.Enum('junior', 'mid', 'senior', 'lead', 'any', name='experiencelevel'), nullable=False),
    sa.Column('technologies', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('locations', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('remote_preference', sa.Enum('remote', 'hybrid', 'onsite', 'any', name='remotepreference'), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('employment_type', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('company_size', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('industries', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('excluded_companies', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('whitelisted_companies', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('application_daily_limit', sa.Integer(), nullable=False),
    sa.Column('auto_apply', sa.Boolean(), nullable=False),
    sa.Column('ai_provider_preference', sa.Enum('claude', 'openai', 'gemini', name='aiproviderpreference'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_preferences')
    # ### end Alembic commands ###
